/* AULA 1 
CRIAR BASE DE DADOS
CONECTAR NELA
CRIAR PRIMEIRA TABELA
MOSTRAR
DESCREVER
*/

/* Modelagem basica */
/* No MySQL o comentário é com # */

/* Primeiro vamos cadastrar um cliente e assim vamos determinar o que é preciso */

CLIENTE

NOME CARACTER(30)
CPF NUMERICO(11)
EMAIL CARACTER(30)
TELEFONE CARACTER(30)
SEXO CARACTER(1)
ENDERECO CARACTER(100)

/* PROCESSOS DE MODELAGEM */

/* ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO 01

/**/
MODELAGEM LÓGICA - PROGRAMAS COMO BR MODELO 02

/*AD e DBA*/
MODELAGEM FÍSICA - SCRIPT DO BANCO DE DADOS

/* MODELO FISICO */

/* CRIANDO UM BANCO */

CREATE DATABASE PROJETO;

/* CONECTANDO */

USE PROJETO;

/* CRIANDO A TABELA */

CREATE TABLE CLIENTE(

	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)

);

/*VERIFICANDO AS TABELAS*/

SHOW TABLES;

/* DESCREVENDO TABELAS */

DESC CLIENTE;